# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    api.pp.client: 'AaXpOTiDYtDlu1j4CHTmd5a-kqpbPs6fds3kC0Sk1d3qfYHVN1TexTsiWWf2o0l0ToLVP70Bx9bFlikM'
    api.pp.secret: 'EBIYQoByzD70OQdMR3OHhcomY_0UlQ3XoPk9yIGRtLLI3fU6DBgYhedFeOxDnTElDWD6S5M7-bbDSZce'
    api.pp.uri: 'https://api.sandbox.paypal.com'
    api.six.key: 'QVBJXzI0Nzk2NF83NzYwMjk2MTpac3B0ODhnU1R4dHFLcGZK'
    api.six.user: 'API_247964_08724734'
    api.six.uri: 'https://test.saferpay.com/api'
    api.six.customer: '247964'
    api.six.terminal: '17966309'
    api.geo.uri: 'http://ip-api.com/json'
    storage.img: '/var/www/html/storage/img'
    app.supported_locales: ['en', 'de', 'fr']
    api.city.name: parentsolo
    api.city.key: so03232fa975a927abf4d5e48b2e17968981c1c221

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Mailer\:
        resource: '../src/Mailer'
        arguments: ['swiftmailer.mailer.default', '@twig']
        public: true

    App\EventListener\ExceptionListener:
        tags :
            - { name: kernel.event_listener, event: kernel.exception }
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    backndev\sixpayment\Command\:
        resource: '../vendor/backndev/sixpayment/Command'
        public: true

    backndev\paypal\Subscription\:
        resource: '../vendor/backndev/paypal/Subscription'
        arguments: ['@security.context_listener']
        public: true

    App\Service\:
        resource: '../src/Service'
        arguments: ['@doctrine.orm.entity_manager', '@swiftmailer.mailer.default']

    App\EventListener\LocaleSubscriber:
        arguments: ['%kernel.default_locale%']
        # uncomment the next line if you are not using autoconfigure
        tags: [kernel.event_subscriber]