INSERT INTO parentsolo.canton (id, name, code) VALUES (2, 'Vaud', 1);
INSERT INTO parentsolo.canton (id, name, code) VALUES (3, 'Genève', 2);
INSERT INTO parentsolo.canton (id, name, code) VALUES (4, 'Neuchâtel', 3);
INSERT INTO parentsolo.canton (id, name, code) VALUES (5, 'Fribourg', 4);
INSERT INTO parentsolo.canton (id, name, code) VALUES (6, 'Jura', 5);
INSERT INTO parentsolo.canton (id, name, code) VALUES (7, 'Valais', 6);
INSERT INTO parentsolo.canton (id, name, code) VALUES (8, 'Tessin', 7);
INSERT INTO parentsolo.canton (id, name, code) VALUES (9, 'Grisons', 8);
INSERT INTO parentsolo.canton (id, name, code) VALUES (10, 'Berne', 9);
INSERT INTO parentsolo.canton (id, name, code) VALUES (11, 'Appenzell Rhodes-Extérieures', 10);
INSERT INTO parentsolo.canton (id, name, code) VALUES (12, 'Appenzell Rhodes-Intérieures', 11);
INSERT INTO parentsolo.canton (id, name, code) VALUES (13, 'Argovie', 12);
INSERT INTO parentsolo.canton (id, name, code) VALUES (14, 'Bâle-Campagne', 13);
INSERT INTO parentsolo.canton (id, name, code) VALUES (15, 'Bâle-Ville', 14);
INSERT INTO parentsolo.canton (id, name, code) VALUES (16, 'Glaris', 15);
INSERT INTO parentsolo.canton (id, name, code) VALUES (17, 'Lucerne', 16);
INSERT INTO parentsolo.canton (id, name, code) VALUES (18, 'Nidwald', 17);
INSERT INTO parentsolo.canton (id, name, code) VALUES (19, 'Obwald', 18);
INSERT INTO parentsolo.canton (id, name, code) VALUES (20, 'Saint-Gall', 19);
INSERT INTO parentsolo.canton (id, name, code) VALUES (21, 'Schaffhouse', 20);
INSERT INTO parentsolo.canton (id, name, code) VALUES (22, 'Schwytz', 21);
INSERT INTO parentsolo.canton (id, name, code) VALUES (23, 'Soleure', 22);
INSERT INTO parentsolo.canton (id, name, code) VALUES (24, 'Thurgovie', 23);
INSERT INTO parentsolo.canton (id, name, code) VALUES (25, 'Uri', 24);
INSERT INTO parentsolo.canton (id, name, code) VALUES (26, 'Zoug', 25);
INSERT INTO parentsolo.canton (id, name, code) VALUES (27, 'Zurich', 26);